name: First Workflow # the name of the workflow

on: workflow_dispatch # the clause on when the workflow will be run(in this case, mannualy)

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: |
          echo "Hello World!"
          echo "Hello World 2!
      - name: Print Goobye
        run: echo "Done - bye!"
